package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("sssss")
    void generatedTest() {
        step("Открываем https://tdconf.ru/2022.", () -> {
            step("// todo: just add selenium action");
        });

        step("Выбираем 29 апреля в расписании.", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверяем что в списке докладов есть «Автоматизируя автоматизацию тестирования».", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://tdconf.ru/2022'", () ->
            open("https://tdconf.ru/2022"));

        step("Page title should have text 'TestDriven Conf 2022 - Профессиональная конференция, посвящённая автоматизации в тестировании и рядом'", () -> {
            String expectedTitle = "TestDriven Conf 2022 - Профессиональная конференция, посвящённая автоматизации в тестировании и рядом";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://tdconf.ru/2022'", () ->
            open("https://tdconf.ru/2022"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}